
package com.mamlaka.paymentgatewayserver.database.model;

/**
 *
 * @author Julius
 */

public enum Status {
    CLIENT_CREATED, CLIENT_ACTIVATED, CLIENT_DEACTIVATED, ERROR_CREATING_CLIENT,
    ACCOUNT_CREATED, ACCOUNT_ACTIVATED, ACCOUNT_DEACTIVATED, ERROR_CREATING_ACCOUNT,
    TRANS_SUBMITTED, TRANS_SUCCESS, TRANS_FAIL
}